package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMON_RESULT".
 */
public class CommonResult {

    private Long id;
    private Integer type;
    private Integer set;
    private byte[] reps;
    private Integer load;
    private Integer RM;
    private Long duration;
    private Long restTime;
    private Long wasteTime;
    private byte[] newRecord;

    public CommonResult() {
    }

    public CommonResult(Long id) {
        this.id = id;
    }

    public CommonResult(Long id, Integer type, Integer set, byte[] reps, Integer load, Integer RM, Long duration, Long restTime, Long wasteTime, byte[] newRecord) {
        this.id = id;
        this.type = type;
        this.set = set;
        this.reps = reps;
        this.load = load;
        this.RM = RM;
        this.duration = duration;
        this.restTime = restTime;
        this.wasteTime = wasteTime;
        this.newRecord = newRecord;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSet() {
        return set;
    }

    public void setSet(Integer set) {
        this.set = set;
    }

    public byte[] getReps() {
        return reps;
    }

    public void setReps(byte[] reps) {
        this.reps = reps;
    }

    public Integer getLoad() {
        return load;
    }

    public void setLoad(Integer load) {
        this.load = load;
    }

    public Integer getRM() {
        return RM;
    }

    public void setRM(Integer RM) {
        this.RM = RM;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getRestTime() {
        return restTime;
    }

    public void setRestTime(Long restTime) {
        this.restTime = restTime;
    }

    public Long getWasteTime() {
        return wasteTime;
    }

    public void setWasteTime(Long wasteTime) {
        this.wasteTime = wasteTime;
    }

    public byte[] getNewRecord() {
        return newRecord;
    }

    public void setNewRecord(byte[] newRecord) {
        this.newRecord = newRecord;
    }

}
