package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "COMMON_RESULT".
 */
public class CommonResult implements Serializable {

    private Long id;
    private Integer type;
    private Integer set;
    private byte[] reps;
    private byte[] rep_duration;
    private Integer load;
    private Integer RM;
    private Long duration;
    private Long restTime;
    private Long wasteTime;
    private byte[] newRecord;
    private Integer mileage;
    private Integer speed;
    private Integer cadence;
    private byte[] speedPerMinute;
    private Integer minuteCount;
    private byte[] cadencePerKm;
    private Integer stride;
    private byte[] kneePress;
    private Long step;
    private byte[] vertOsci;
    private byte[] emgDecrease;
    private Long calorie;
    private byte[] stability;
    private Long startTime;
    private Long endTime;
    private Double startlatitude;
    private Double startlongitude;
    private Double endlatitude;
    private Double endlongitude;
    private String latLngs;
    private byte[] notification;
    private String comment;
    private String picturePath;
<<<<<<< HEAD
    private String dataFileName;
=======
>>>>>>> KeenBrace_Android/master
    private Integer weight;
    private Integer bodyFat;
    private Integer waist;
    private Integer chest;
    private Integer arms;
    private Integer forArms;
    private Integer shoulder;
    private Integer hips;
    private Integer thighs;
    private Integer calves;
    private Integer neck;

    public CommonResult() {
    }

    public CommonResult(Long id) {
        this.id = id;
    }

<<<<<<< HEAD
    public CommonResult(Long id, Integer type, Integer set, byte[] reps, byte[] rep_duration, Integer load, Integer RM, Long duration, Long restTime, Long wasteTime, byte[] newRecord, Integer mileage, Integer speed, Integer cadence, byte[] speedPerMinute, Integer minuteCount, byte[] cadencePerKm, Integer stride, byte[] kneePress, Long step, byte[] vertOsci, byte[] emgDecrease, Long calorie, byte[] stability, Long startTime, Long endTime, Double startlatitude, Double startlongitude, Double endlatitude, Double endlongitude, String latLngs, byte[] notification, String comment, String picturePath, String dataFileName, Integer weight, Integer bodyFat, Integer waist, Integer chest, Integer arms, Integer forArms, Integer shoulder, Integer hips, Integer thighs, Integer calves, Integer neck) {
=======
    public CommonResult(Long id, Integer type, Integer set, byte[] reps, byte[] rep_duration, Integer load, Integer RM, Long duration, Long restTime, Long wasteTime, byte[] newRecord, Integer mileage, Integer speed, Integer cadence, byte[] speedPerMinute, Integer minuteCount, byte[] cadencePerKm, Integer stride, byte[] kneePress, Long step, byte[] vertOsci, byte[] emgDecrease, Long calorie, byte[] stability, Long startTime, Long endTime, Double startlatitude, Double startlongitude, Double endlatitude, Double endlongitude, String latLngs, byte[] notification, String comment, String picturePath, Integer weight, Integer bodyFat, Integer waist, Integer chest, Integer arms, Integer forArms, Integer shoulder, Integer hips, Integer thighs, Integer calves, Integer neck) {
>>>>>>> KeenBrace_Android/master
        this.id = id;
        this.type = type;
        this.set = set;
        this.reps = reps;
        this.rep_duration = rep_duration;
        this.load = load;
        this.RM = RM;
        this.duration = duration;
        this.restTime = restTime;
        this.wasteTime = wasteTime;
        this.newRecord = newRecord;
        this.mileage = mileage;
        this.speed = speed;
        this.cadence = cadence;
        this.speedPerMinute = speedPerMinute;
        this.minuteCount = minuteCount;
        this.cadencePerKm = cadencePerKm;
        this.stride = stride;
        this.kneePress = kneePress;
        this.step = step;
        this.vertOsci = vertOsci;
        this.emgDecrease = emgDecrease;
        this.calorie = calorie;
        this.stability = stability;
        this.startTime = startTime;
        this.endTime = endTime;
        this.startlatitude = startlatitude;
        this.startlongitude = startlongitude;
        this.endlatitude = endlatitude;
        this.endlongitude = endlongitude;
        this.latLngs = latLngs;
        this.notification = notification;
        this.comment = comment;
        this.picturePath = picturePath;
<<<<<<< HEAD
        this.dataFileName = dataFileName;
=======
>>>>>>> KeenBrace_Android/master
        this.weight = weight;
        this.bodyFat = bodyFat;
        this.waist = waist;
        this.chest = chest;
        this.arms = arms;
        this.forArms = forArms;
        this.shoulder = shoulder;
        this.hips = hips;
        this.thighs = thighs;
        this.calves = calves;
        this.neck = neck;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSet() {
        return set;
    }

    public void setSet(Integer set) {
        this.set = set;
    }

    public byte[] getReps() {
        return reps;
    }

    public void setReps(byte[] reps) {
        this.reps = reps;
    }

    public byte[] getRep_duration() {
        return rep_duration;
    }

    public void setRep_duration(byte[] rep_duration) {
        this.rep_duration = rep_duration;
    }

    public Integer getLoad() {
        return load;
    }

    public void setLoad(Integer load) {
        this.load = load;
    }

    public Integer getRM() {
        return RM;
    }

    public void setRM(Integer RM) {
        this.RM = RM;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getRestTime() {
        return restTime;
    }

    public void setRestTime(Long restTime) {
        this.restTime = restTime;
    }

    public Long getWasteTime() {
        return wasteTime;
    }

    public void setWasteTime(Long wasteTime) {
        this.wasteTime = wasteTime;
    }

    public byte[] getNewRecord() {
        return newRecord;
    }

    public void setNewRecord(byte[] newRecord) {
        this.newRecord = newRecord;
    }

    public Integer getMileage() {
        return mileage;
    }

    public void setMileage(Integer mileage) {
        this.mileage = mileage;
    }

    public Integer getSpeed() {
        return speed;
    }

    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    public Integer getCadence() {
        return cadence;
    }

    public void setCadence(Integer cadence) {
        this.cadence = cadence;
    }

    public byte[] getSpeedPerMinute() {
        return speedPerMinute;
    }

    public void setSpeedPerMinute(byte[] speedPerMinute) {
        this.speedPerMinute = speedPerMinute;
    }

    public Integer getMinuteCount() {
        return minuteCount;
    }

    public void setMinuteCount(Integer minuteCount) {
        this.minuteCount = minuteCount;
    }

    public byte[] getCadencePerKm() {
        return cadencePerKm;
    }

    public void setCadencePerKm(byte[] cadencePerKm) {
        this.cadencePerKm = cadencePerKm;
    }

    public Integer getStride() {
        return stride;
    }

    public void setStride(Integer stride) {
        this.stride = stride;
    }

    public byte[] getKneePress() {
        return kneePress;
    }

    public void setKneePress(byte[] kneePress) {
        this.kneePress = kneePress;
    }

    public Long getStep() {
        return step;
    }

    public void setStep(Long step) {
        this.step = step;
    }

    public byte[] getVertOsci() {
        return vertOsci;
    }

    public void setVertOsci(byte[] vertOsci) {
        this.vertOsci = vertOsci;
    }

    public byte[] getEmgDecrease() {
        return emgDecrease;
    }

    public void setEmgDecrease(byte[] emgDecrease) {
        this.emgDecrease = emgDecrease;
    }

    public Long getCalorie() {
        return calorie;
    }

    public void setCalorie(Long calorie) {
        this.calorie = calorie;
    }

    public byte[] getStability() {
        return stability;
    }

    public void setStability(byte[] stability) {
        this.stability = stability;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Double getStartlatitude() {
        return startlatitude;
    }

    public void setStartlatitude(Double startlatitude) {
        this.startlatitude = startlatitude;
    }

    public Double getStartlongitude() {
        return startlongitude;
    }

    public void setStartlongitude(Double startlongitude) {
        this.startlongitude = startlongitude;
    }

    public Double getEndlatitude() {
        return endlatitude;
    }

    public void setEndlatitude(Double endlatitude) {
        this.endlatitude = endlatitude;
    }

    public Double getEndlongitude() {
        return endlongitude;
    }

    public void setEndlongitude(Double endlongitude) {
        this.endlongitude = endlongitude;
    }

    public String getLatLngs() {
        return latLngs;
    }

    public void setLatLngs(String latLngs) {
        this.latLngs = latLngs;
    }

    public byte[] getNotification() {
        return notification;
    }

    public void setNotification(byte[] notification) {
        this.notification = notification;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getPicturePath() {
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

<<<<<<< HEAD
    public String getDataFileName() {
        return dataFileName;
    }

    public void setDataFileName(String dataFileName) {
        this.dataFileName = dataFileName;
    }

=======
>>>>>>> KeenBrace_Android/master
    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getBodyFat() {
        return bodyFat;
    }

    public void setBodyFat(Integer bodyFat) {
        this.bodyFat = bodyFat;
    }

    public Integer getWaist() {
        return waist;
    }

    public void setWaist(Integer waist) {
        this.waist = waist;
    }

    public Integer getChest() {
        return chest;
    }

    public void setChest(Integer chest) {
        this.chest = chest;
    }

    public Integer getArms() {
        return arms;
    }

    public void setArms(Integer arms) {
        this.arms = arms;
    }

    public Integer getForArms() {
        return forArms;
    }

    public void setForArms(Integer forArms) {
        this.forArms = forArms;
    }

    public Integer getShoulder() {
        return shoulder;
    }

    public void setShoulder(Integer shoulder) {
        this.shoulder = shoulder;
    }

    public Integer getHips() {
        return hips;
    }

    public void setHips(Integer hips) {
        this.hips = hips;
    }

    public Integer getThighs() {
        return thighs;
    }

    public void setThighs(Integer thighs) {
        this.thighs = thighs;
    }

    public Integer getCalves() {
        return calves;
    }

    public void setCalves(Integer calves) {
        this.calves = calves;
    }

    public Integer getNeck() {
        return neck;
    }

    public void setNeck(Integer neck) {
        this.neck = neck;
    }

}
