package com.keenbrace.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.keenbrace.greendao.User;
import com.keenbrace.greendao.RunWaring;
import com.keenbrace.greendao.KeenBrace;

import com.keenbrace.greendao.UserDao;
import com.keenbrace.greendao.RunWaringDao;
import com.keenbrace.greendao.KeenBraceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig runWaringDaoConfig;
    private final DaoConfig keenBraceDaoConfig;

    private final UserDao userDao;
    private final RunWaringDao runWaringDao;
    private final KeenBraceDao keenBraceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        runWaringDaoConfig = daoConfigMap.get(RunWaringDao.class).clone();
        runWaringDaoConfig.initIdentityScope(type);

        keenBraceDaoConfig = daoConfigMap.get(KeenBraceDao.class).clone();
        keenBraceDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        runWaringDao = new RunWaringDao(runWaringDaoConfig, this);
        keenBraceDao = new KeenBraceDao(keenBraceDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(RunWaring.class, runWaringDao);
        registerDao(KeenBrace.class, keenBraceDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        runWaringDaoConfig.getIdentityScope().clear();
        keenBraceDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RunWaringDao getRunWaringDao() {
        return runWaringDao;
    }

    public KeenBraceDao getKeenBraceDao() {
        return keenBraceDao;
    }

}
