package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY_RECORD".
 */
public class HistoryRecord {

    private Long id;
    private Long triceps;
    private Long biceps;
    private Long shoulder;
    private Long forearm;
    private Long chest;
    private Long back;
    private Long abs;
    private Long glutes;
    private Long upperleg;
    private Long lowerleg;
    private Long cardio;
    private Long tricepsReps;
    private Long bicepsReps;
    private Long shoulderReps;
    private Long forearmReps;
    private Long chestReps;
    private Long backReps;
    private Long absReps;
    private Long glutesReps;
    private Long upperlegReps;
    private Long lowerlegReps;
    private Long totalWorkout;
    private Long totalDistance;
    private Integer averSpeed;
    private Long totalCalorie;
    private Long totalTime;
    private Integer RM;
    private Integer longestDistance;
    private Long longestTime;
    private Integer fastestSpeed;
    private Long mostCalorie;

    public HistoryRecord() {
    }

    public HistoryRecord(Long id) {
        this.id = id;
    }

    public HistoryRecord(Long id, Long triceps, Long biceps, Long shoulder, Long forearm, Long chest, Long back, Long abs, Long glutes, Long upperleg, Long lowerleg, Long cardio, Long tricepsReps, Long bicepsReps, Long shoulderReps, Long forearmReps, Long chestReps, Long backReps, Long absReps, Long glutesReps, Long upperlegReps, Long lowerlegReps, Long totalWorkout, Long totalDistance, Integer averSpeed, Long totalCalorie, Long totalTime, Integer RM, Integer longestDistance, Long longestTime, Integer fastestSpeed, Long mostCalorie) {
        this.id = id;
        this.triceps = triceps;
        this.biceps = biceps;
        this.shoulder = shoulder;
        this.forearm = forearm;
        this.chest = chest;
        this.back = back;
        this.abs = abs;
        this.glutes = glutes;
        this.upperleg = upperleg;
        this.lowerleg = lowerleg;
        this.cardio = cardio;
        this.tricepsReps = tricepsReps;
        this.bicepsReps = bicepsReps;
        this.shoulderReps = shoulderReps;
        this.forearmReps = forearmReps;
        this.chestReps = chestReps;
        this.backReps = backReps;
        this.absReps = absReps;
        this.glutesReps = glutesReps;
        this.upperlegReps = upperlegReps;
        this.lowerlegReps = lowerlegReps;
        this.totalWorkout = totalWorkout;
        this.totalDistance = totalDistance;
        this.averSpeed = averSpeed;
        this.totalCalorie = totalCalorie;
        this.totalTime = totalTime;
        this.RM = RM;
        this.longestDistance = longestDistance;
        this.longestTime = longestTime;
        this.fastestSpeed = fastestSpeed;
        this.mostCalorie = mostCalorie;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTriceps() {
        return triceps;
    }

    public void setTriceps(Long triceps) {
        this.triceps = triceps;
    }

    public Long getBiceps() {
        return biceps;
    }

    public void setBiceps(Long biceps) {
        this.biceps = biceps;
    }

    public Long getShoulder() {
        return shoulder;
    }

    public void setShoulder(Long shoulder) {
        this.shoulder = shoulder;
    }

    public Long getForearm() {
        return forearm;
    }

    public void setForearm(Long forearm) {
        this.forearm = forearm;
    }

    public Long getChest() {
        return chest;
    }

    public void setChest(Long chest) {
        this.chest = chest;
    }

    public Long getBack() {
        return back;
    }

    public void setBack(Long back) {
        this.back = back;
    }

    public Long getAbs() {
        return abs;
    }

    public void setAbs(Long abs) {
        this.abs = abs;
    }

    public Long getGlutes() {
        return glutes;
    }

    public void setGlutes(Long glutes) {
        this.glutes = glutes;
    }

    public Long getUpperleg() {
        return upperleg;
    }

    public void setUpperleg(Long upperleg) {
        this.upperleg = upperleg;
    }

    public Long getLowerleg() {
        return lowerleg;
    }

    public void setLowerleg(Long lowerleg) {
        this.lowerleg = lowerleg;
    }

    public Long getCardio() {
        return cardio;
    }

    public void setCardio(Long cardio) {
        this.cardio = cardio;
    }

    public Long getTricepsReps() {
        return tricepsReps;
    }

    public void setTricepsReps(Long tricepsReps) {
        this.tricepsReps = tricepsReps;
    }

    public Long getBicepsReps() {
        return bicepsReps;
    }

    public void setBicepsReps(Long bicepsReps) {
        this.bicepsReps = bicepsReps;
    }

    public Long getShoulderReps() {
        return shoulderReps;
    }

    public void setShoulderReps(Long shoulderReps) {
        this.shoulderReps = shoulderReps;
    }

    public Long getForearmReps() {
        return forearmReps;
    }

    public void setForearmReps(Long forearmReps) {
        this.forearmReps = forearmReps;
    }

    public Long getChestReps() {
        return chestReps;
    }

    public void setChestReps(Long chestReps) {
        this.chestReps = chestReps;
    }

    public Long getBackReps() {
        return backReps;
    }

    public void setBackReps(Long backReps) {
        this.backReps = backReps;
    }

    public Long getAbsReps() {
        return absReps;
    }

    public void setAbsReps(Long absReps) {
        this.absReps = absReps;
    }

    public Long getGlutesReps() {
        return glutesReps;
    }

    public void setGlutesReps(Long glutesReps) {
        this.glutesReps = glutesReps;
    }

    public Long getUpperlegReps() {
        return upperlegReps;
    }

    public void setUpperlegReps(Long upperlegReps) {
        this.upperlegReps = upperlegReps;
    }

    public Long getLowerlegReps() {
        return lowerlegReps;
    }

    public void setLowerlegReps(Long lowerlegReps) {
        this.lowerlegReps = lowerlegReps;
    }

    public Long getTotalWorkout() {
        return totalWorkout;
    }

    public void setTotalWorkout(Long totalWorkout) {
        this.totalWorkout = totalWorkout;
    }

    public Long getTotalDistance() {
        return totalDistance;
    }

    public void setTotalDistance(Long totalDistance) {
        this.totalDistance = totalDistance;
    }

    public Integer getAverSpeed() {
        return averSpeed;
    }

    public void setAverSpeed(Integer averSpeed) {
        this.averSpeed = averSpeed;
    }

    public Long getTotalCalorie() {
        return totalCalorie;
    }

    public void setTotalCalorie(Long totalCalorie) {
        this.totalCalorie = totalCalorie;
    }

    public Long getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(Long totalTime) {
        this.totalTime = totalTime;
    }

    public Integer getRM() {
        return RM;
    }

    public void setRM(Integer RM) {
        this.RM = RM;
    }

    public Integer getLongestDistance() {
        return longestDistance;
    }

    public void setLongestDistance(Integer longestDistance) {
        this.longestDistance = longestDistance;
    }

    public Long getLongestTime() {
        return longestTime;
    }

    public void setLongestTime(Long longestTime) {
        this.longestTime = longestTime;
    }

    public Integer getFastestSpeed() {
        return fastestSpeed;
    }

    public void setFastestSpeed(Integer fastestSpeed) {
        this.fastestSpeed = fastestSpeed;
    }

    public Long getMostCalorie() {
        return mostCalorie;
    }

    public void setMostCalorie(Long mostCalorie) {
        this.mostCalorie = mostCalorie;
    }

}
