package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "KEEN_BRACE".
 */
public class KeenBrace implements Serializable{

    private Long id;
    private Long userID;
    private Integer type;
    private Long startTime;
    private Long timelength;
    private Integer sumscore;
    private Integer cadence;
    private Integer stride;
    private Integer mileage;
    private String fileName;
    private Long endTime;
    private String latLngs;
    private Integer sumwarings;
    private Double latitude;
    private Double longitude;
    private Double endlatitude;
    private Double endlongitude;
    private Integer state;

    public KeenBrace() {
    }

    public KeenBrace(Long id) {
        this.id = id;
    }

    public KeenBrace(Long id, Long userID, Integer type, Long startTime, Long timelength, Integer sumscore, Integer cadence, Integer stride, Integer mileage, String fileName, Long endTime, String latLngs, Integer sumwarings, Double latitude, Double longitude, Double endlatitude, Double endlongitude, Integer state) {
        this.id = id;
        this.userID = userID;
        this.type = type;
        this.startTime = startTime;
        this.timelength = timelength;
        this.sumscore = sumscore;
        this.cadence = cadence;
        this.stride = stride;
        this.mileage = mileage;
        this.fileName = fileName;
        this.endTime = endTime;
        this.latLngs = latLngs;
        this.sumwarings = sumwarings;
        this.latitude = latitude;
        this.longitude = longitude;
        this.endlatitude = endlatitude;
        this.endlongitude = endlongitude;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getTimelength() {
        return timelength;
    }

    public void setTimelength(Long timelength) {
        this.timelength = timelength;
    }

    public Integer getSumscore() {
        return sumscore;
    }

    public void setSumscore(Integer sumscore) {
        this.sumscore = sumscore;
    }

    public Integer getCadence() {
        return cadence;
    }

    public void setCadence(Integer cadence) {
        this.cadence = cadence;
    }

    public Integer getStride() {
        return stride;
    }

    public void setStride(Integer stride) {
        this.stride = stride;
    }

    public Integer getMileage() {
        return mileage;
    }

    public void setMileage(Integer mileage) {
        this.mileage = mileage;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public String getLatLngs() {
        return latLngs;
    }

    public void setLatLngs(String latLngs) {
        this.latLngs = latLngs;
    }

    public Integer getSumwarings() {
        return sumwarings;
    }

    public void setSumwarings(Integer sumwarings) {
        this.sumwarings = sumwarings;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getEndlatitude() {
        return endlatitude;
    }

    public void setEndlatitude(Double endlatitude) {
        this.endlatitude = endlatitude;
    }

    public Double getEndlongitude() {
        return endlongitude;
    }

    public void setEndlongitude(Double endlongitude) {
        this.endlongitude = endlongitude;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
