package com.keenbrace.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.keenbrace.greendao.LongPlan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LONG_PLAN".
*/
public class LongPlanDao extends AbstractDao<LongPlan, Long> {

    public static final String TABLENAME = "LONG_PLAN";

    /**
     * Properties of entity LongPlan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LongPlanName = new Property(1, String.class, "LongPlanName", false, "LONG_PLAN_NAME");
        public final static Property Weekdays = new Property(2, Integer.class, "weekdays", false, "WEEKDAYS");
        public final static Property Start_date = new Property(3, java.util.Date.class, "start_date", false, "START_DATE");
        public final static Property End_date = new Property(4, java.util.Date.class, "end_date", false, "END_DATE");
        public final static Property Types = new Property(5, byte[].class, "types", false, "TYPES");
        public final static Property Times = new Property(6, Integer.class, "times", false, "TIMES");
        public final static Property Interval = new Property(7, byte[].class, "interval", false, "INTERVAL");
        public final static Property FinishStatus = new Property(8, byte[].class, "finishStatus", false, "FINISH_STATUS");
        public final static Property TrainIDset = new Property(9, byte[].class, "trainIDset", false, "TRAIN_IDSET");
    };


    public LongPlanDao(DaoConfig config) {
        super(config);
    }
    
    public LongPlanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LONG_PLAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LONG_PLAN_NAME\" TEXT UNIQUE ," + // 1: LongPlanName
                "\"WEEKDAYS\" INTEGER," + // 2: weekdays
                "\"START_DATE\" INTEGER," + // 3: start_date
                "\"END_DATE\" INTEGER," + // 4: end_date
                "\"TYPES\" BLOB," + // 5: types
                "\"TIMES\" INTEGER," + // 6: times
                "\"INTERVAL\" BLOB," + // 7: interval
                "\"FINISH_STATUS\" BLOB," + // 8: finishStatus
                "\"TRAIN_IDSET\" BLOB);"); // 9: trainIDset
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LONG_PLAN\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LongPlan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String LongPlanName = entity.getLongPlanName();
        if (LongPlanName != null) {
            stmt.bindString(2, LongPlanName);
        }
 
        Integer weekdays = entity.getWeekdays();
        if (weekdays != null) {
            stmt.bindLong(3, weekdays);
        }
 
        java.util.Date start_date = entity.getStart_date();
        if (start_date != null) {
            stmt.bindLong(4, start_date.getTime());
        }
 
        java.util.Date end_date = entity.getEnd_date();
        if (end_date != null) {
            stmt.bindLong(5, end_date.getTime());
        }
 
        byte[] types = entity.getTypes();
        if (types != null) {
            stmt.bindBlob(6, types);
        }
 
        Integer times = entity.getTimes();
        if (times != null) {
            stmt.bindLong(7, times);
        }
 
        byte[] interval = entity.getInterval();
        if (interval != null) {
            stmt.bindBlob(8, interval);
        }
 
        byte[] finishStatus = entity.getFinishStatus();
        if (finishStatus != null) {
            stmt.bindBlob(9, finishStatus);
        }
 
        byte[] trainIDset = entity.getTrainIDset();
        if (trainIDset != null) {
            stmt.bindBlob(10, trainIDset);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public LongPlan readEntity(Cursor cursor, int offset) {
        LongPlan entity = new LongPlan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // LongPlanName
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // weekdays
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // start_date
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // end_date
            cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5), // types
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // times
            cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7), // interval
            cursor.isNull(offset + 8) ? null : cursor.getBlob(offset + 8), // finishStatus
            cursor.isNull(offset + 9) ? null : cursor.getBlob(offset + 9) // trainIDset
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LongPlan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLongPlanName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeekdays(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setStart_date(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setEnd_date(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setTypes(cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5));
        entity.setTimes(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setInterval(cursor.isNull(offset + 7) ? null : cursor.getBlob(offset + 7));
        entity.setFinishStatus(cursor.isNull(offset + 8) ? null : cursor.getBlob(offset + 8));
        entity.setTrainIDset(cursor.isNull(offset + 9) ? null : cursor.getBlob(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LongPlan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LongPlan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
