package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LONG_PLAN".
 */
public class LongPlan {

    private Long id;
    private Integer weekdays;
    private java.util.Date start_date;
    private java.util.Date end_date;
    private byte[] types;
    private Integer times;
    private byte[] interval;
    private byte[] finishStatus;
    private byte[] trainIDset;

    public LongPlan() {
    }

    public LongPlan(Long id) {
        this.id = id;
    }

    public LongPlan(Long id, Integer weekdays, java.util.Date start_date, java.util.Date end_date, byte[] types, Integer times, byte[] interval, byte[] finishStatus, byte[] trainIDset) {
        this.id = id;
        this.weekdays = weekdays;
        this.start_date = start_date;
        this.end_date = end_date;
        this.types = types;
        this.times = times;
        this.interval = interval;
        this.finishStatus = finishStatus;
        this.trainIDset = trainIDset;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getWeekdays() {
        return weekdays;
    }

    public void setWeekdays(Integer weekdays) {
        this.weekdays = weekdays;
    }

    public java.util.Date getStart_date() {
        return start_date;
    }

    public void setStart_date(java.util.Date start_date) {
        this.start_date = start_date;
    }

    public java.util.Date getEnd_date() {
        return end_date;
    }

    public void setEnd_date(java.util.Date end_date) {
        this.end_date = end_date;
    }

    public byte[] getTypes() {
        return types;
    }

    public void setTypes(byte[] types) {
        this.types = types;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public byte[] getInterval() {
        return interval;
    }

    public void setInterval(byte[] interval) {
        this.interval = interval;
    }

    public byte[] getFinishStatus() {
        return finishStatus;
    }

    public void setFinishStatus(byte[] finishStatus) {
        this.finishStatus = finishStatus;
    }

    public byte[] getTrainIDset() {
        return trainIDset;
    }

    public void setTrainIDset(byte[] trainIDset) {
        this.trainIDset = trainIDset;
    }

}
