package com.keenbrace.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.keenbrace.greendao.RunResult;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RUN_RESULT".
*/
public class RunResultDao extends AbstractDao<RunResult, Long> {

    public static final String TABLENAME = "RUN_RESULT";

    /**
     * Properties of entity RunResult.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Mileage = new Property(1, Integer.class, "mileage", false, "MILEAGE");
        public final static Property Duration = new Property(2, Long.class, "duration", false, "DURATION");
        public final static Property Speed = new Property(3, Integer.class, "speed", false, "SPEED");
        public final static Property Cadence = new Property(4, Integer.class, "cadence", false, "CADENCE");
        public final static Property SpeedPerKm = new Property(5, byte[].class, "speedPerKm", false, "SPEED_PER_KM");
        public final static Property CadencePerKm = new Property(6, byte[].class, "cadencePerKm", false, "CADENCE_PER_KM");
        public final static Property Stride = new Property(7, Integer.class, "stride", false, "STRIDE");
        public final static Property KneePress = new Property(8, Integer.class, "kneePress", false, "KNEE_PRESS");
        public final static Property Step = new Property(9, Long.class, "step", false, "STEP");
        public final static Property VertOsci = new Property(10, Integer.class, "vertOsci", false, "VERT_OSCI");
        public final static Property EmgDecrease = new Property(11, Integer.class, "emgDecrease", false, "EMG_DECREASE");
        public final static Property Calorie = new Property(12, Long.class, "calorie", false, "CALORIE");
        public final static Property Stability = new Property(13, Integer.class, "stability", false, "STABILITY");
        public final static Property StartTime = new Property(14, Long.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(15, Long.class, "endTime", false, "END_TIME");
        public final static Property Startlatitude = new Property(16, Double.class, "startlatitude", false, "STARTLATITUDE");
        public final static Property Startlongitude = new Property(17, Double.class, "startlongitude", false, "STARTLONGITUDE");
        public final static Property Endlatitude = new Property(18, Double.class, "endlatitude", false, "ENDLATITUDE");
        public final static Property Endlongitude = new Property(19, Double.class, "endlongitude", false, "ENDLONGITUDE");
        public final static Property LatLngs = new Property(20, String.class, "latLngs", false, "LAT_LNGS");
        public final static Property Notification = new Property(21, byte[].class, "notification", false, "NOTIFICATION");
    };


    public RunResultDao(DaoConfig config) {
        super(config);
    }
    
    public RunResultDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RUN_RESULT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MILEAGE\" INTEGER," + // 1: mileage
                "\"DURATION\" INTEGER," + // 2: duration
                "\"SPEED\" INTEGER," + // 3: speed
                "\"CADENCE\" INTEGER," + // 4: cadence
                "\"SPEED_PER_KM\" BLOB," + // 5: speedPerKm
                "\"CADENCE_PER_KM\" BLOB," + // 6: cadencePerKm
                "\"STRIDE\" INTEGER," + // 7: stride
                "\"KNEE_PRESS\" INTEGER," + // 8: kneePress
                "\"STEP\" INTEGER," + // 9: step
                "\"VERT_OSCI\" INTEGER," + // 10: vertOsci
                "\"EMG_DECREASE\" INTEGER," + // 11: emgDecrease
                "\"CALORIE\" INTEGER," + // 12: calorie
                "\"STABILITY\" INTEGER," + // 13: stability
                "\"START_TIME\" INTEGER," + // 14: startTime
                "\"END_TIME\" INTEGER," + // 15: endTime
                "\"STARTLATITUDE\" REAL," + // 16: startlatitude
                "\"STARTLONGITUDE\" REAL," + // 17: startlongitude
                "\"ENDLATITUDE\" REAL," + // 18: endlatitude
                "\"ENDLONGITUDE\" REAL," + // 19: endlongitude
                "\"LAT_LNGS\" TEXT," + // 20: latLngs
                "\"NOTIFICATION\" BLOB);"); // 21: notification
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RUN_RESULT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RunResult entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer mileage = entity.getMileage();
        if (mileage != null) {
            stmt.bindLong(2, mileage);
        }
 
        Long duration = entity.getDuration();
        if (duration != null) {
            stmt.bindLong(3, duration);
        }
 
        Integer speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindLong(4, speed);
        }
 
        Integer cadence = entity.getCadence();
        if (cadence != null) {
            stmt.bindLong(5, cadence);
        }
 
        byte[] speedPerKm = entity.getSpeedPerKm();
        if (speedPerKm != null) {
            stmt.bindBlob(6, speedPerKm);
        }
 
        byte[] cadencePerKm = entity.getCadencePerKm();
        if (cadencePerKm != null) {
            stmt.bindBlob(7, cadencePerKm);
        }
 
        Integer stride = entity.getStride();
        if (stride != null) {
            stmt.bindLong(8, stride);
        }
 
        Integer kneePress = entity.getKneePress();
        if (kneePress != null) {
            stmt.bindLong(9, kneePress);
        }
 
        Long step = entity.getStep();
        if (step != null) {
            stmt.bindLong(10, step);
        }
 
        Integer vertOsci = entity.getVertOsci();
        if (vertOsci != null) {
            stmt.bindLong(11, vertOsci);
        }
 
        Integer emgDecrease = entity.getEmgDecrease();
        if (emgDecrease != null) {
            stmt.bindLong(12, emgDecrease);
        }
 
        Long calorie = entity.getCalorie();
        if (calorie != null) {
            stmt.bindLong(13, calorie);
        }
 
        Integer stability = entity.getStability();
        if (stability != null) {
            stmt.bindLong(14, stability);
        }
 
        Long startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindLong(15, startTime);
        }
 
        Long endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindLong(16, endTime);
        }
 
        Double startlatitude = entity.getStartlatitude();
        if (startlatitude != null) {
            stmt.bindDouble(17, startlatitude);
        }
 
        Double startlongitude = entity.getStartlongitude();
        if (startlongitude != null) {
            stmt.bindDouble(18, startlongitude);
        }
 
        Double endlatitude = entity.getEndlatitude();
        if (endlatitude != null) {
            stmt.bindDouble(19, endlatitude);
        }
 
        Double endlongitude = entity.getEndlongitude();
        if (endlongitude != null) {
            stmt.bindDouble(20, endlongitude);
        }
 
        String latLngs = entity.getLatLngs();
        if (latLngs != null) {
            stmt.bindString(21, latLngs);
        }
 
        byte[] notification = entity.getNotification();
        if (notification != null) {
            stmt.bindBlob(22, notification);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RunResult readEntity(Cursor cursor, int offset) {
        RunResult entity = new RunResult( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // mileage
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // duration
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // speed
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // cadence
            cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5), // speedPerKm
            cursor.isNull(offset + 6) ? null : cursor.getBlob(offset + 6), // cadencePerKm
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // stride
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // kneePress
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // step
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // vertOsci
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // emgDecrease
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // calorie
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // stability
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // startTime
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // endTime
            cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16), // startlatitude
            cursor.isNull(offset + 17) ? null : cursor.getDouble(offset + 17), // startlongitude
            cursor.isNull(offset + 18) ? null : cursor.getDouble(offset + 18), // endlatitude
            cursor.isNull(offset + 19) ? null : cursor.getDouble(offset + 19), // endlongitude
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // latLngs
            cursor.isNull(offset + 21) ? null : cursor.getBlob(offset + 21) // notification
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RunResult entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMileage(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDuration(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setSpeed(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setCadence(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSpeedPerKm(cursor.isNull(offset + 5) ? null : cursor.getBlob(offset + 5));
        entity.setCadencePerKm(cursor.isNull(offset + 6) ? null : cursor.getBlob(offset + 6));
        entity.setStride(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setKneePress(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setStep(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setVertOsci(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setEmgDecrease(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setCalorie(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setStability(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setStartTime(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setEndTime(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setStartlatitude(cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16));
        entity.setStartlongitude(cursor.isNull(offset + 17) ? null : cursor.getDouble(offset + 17));
        entity.setEndlatitude(cursor.isNull(offset + 18) ? null : cursor.getDouble(offset + 18));
        entity.setEndlongitude(cursor.isNull(offset + 19) ? null : cursor.getDouble(offset + 19));
        entity.setLatLngs(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setNotification(cursor.isNull(offset + 21) ? null : cursor.getBlob(offset + 21));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RunResult entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RunResult entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
