package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
import java.io.Serializable;

/**
 * Entity mapped to table "RUN_RESULT".
 */
public class RunResult implements Serializable {

    private Long id;
    private Integer mileage;
    private Long duration;
    private Integer speed;
    private Integer cadence;
    private byte[] speedPerKm;
    private byte[] cadencePerKm;
    private Integer stride;
    private Integer kneePress;
    private Long step;
    private Integer vertOsci;
    private Integer emgDecrease;
    private Long calorie;
    private Integer stability;
    private Long startTime;
    private Long endTime;
    private Double startlatitude;
    private Double startlongitude;
    private Double endlatitude;
    private Double endlongitude;
    private String latLngs;
    private byte[] notification;

    public RunResult() {
    }

    public RunResult(Long id) {
        this.id = id;
    }

    public RunResult(Long id, Integer mileage, Long duration, Integer speed, Integer cadence, byte[] speedPerKm, byte[] cadencePerKm, Integer stride, Integer kneePress, Long step, Integer vertOsci, Integer emgDecrease, Long calorie, Integer stability, Long startTime, Long endTime, Double startlatitude, Double startlongitude, Double endlatitude, Double endlongitude, String latLngs, byte[] notification) {
        this.id = id;
        this.mileage = mileage;
        this.duration = duration;
        this.speed = speed;
        this.cadence = cadence;
        this.speedPerKm = speedPerKm;
        this.cadencePerKm = cadencePerKm;
        this.stride = stride;
        this.kneePress = kneePress;
        this.step = step;
        this.vertOsci = vertOsci;
        this.emgDecrease = emgDecrease;
        this.calorie = calorie;
        this.stability = stability;
        this.startTime = startTime;
        this.endTime = endTime;
        this.startlatitude = startlatitude;
        this.startlongitude = startlongitude;
        this.endlatitude = endlatitude;
        this.endlongitude = endlongitude;
        this.latLngs = latLngs;
        this.notification = notification;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMileage() {
        return mileage;
    }

    public void setMileage(Integer mileage) {
        this.mileage = mileage;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Integer getSpeed() {
        return speed;
    }

    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    public Integer getCadence() {
        return cadence;
    }

    public void setCadence(Integer cadence) {
        this.cadence = cadence;
    }

    public byte[] getSpeedPerKm() {
        return speedPerKm;
    }

    public void setSpeedPerKm(byte[] speedPerKm) {
        this.speedPerKm = speedPerKm;
    }

    public byte[] getCadencePerKm() {
        return cadencePerKm;
    }

    public void setCadencePerKm(byte[] cadencePerKm) {
        this.cadencePerKm = cadencePerKm;
    }

    public Integer getStride() {
        return stride;
    }

    public void setStride(Integer stride) {
        this.stride = stride;
    }

    public Integer getKneePress() {
        return kneePress;
    }

    public void setKneePress(Integer kneePress) {
        this.kneePress = kneePress;
    }

    public Long getStep() {
        return step;
    }

    public void setStep(Long step) {
        this.step = step;
    }

    public Integer getVertOsci() {
        return vertOsci;
    }

    public void setVertOsci(Integer vertOsci) {
        this.vertOsci = vertOsci;
    }

    public Integer getEmgDecrease() {
        return emgDecrease;
    }

    public void setEmgDecrease(Integer emgDecrease) {
        this.emgDecrease = emgDecrease;
    }

    public Long getCalorie() {
        return calorie;
    }

    public void setCalorie(Long calorie) {
        this.calorie = calorie;
    }

    public Integer getStability() {
        return stability;
    }

    public void setStability(Integer stability) {
        this.stability = stability;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Double getStartlatitude() {
        return startlatitude;
    }

    public void setStartlatitude(Double startlatitude) {
        this.startlatitude = startlatitude;
    }

    public Double getStartlongitude() {
        return startlongitude;
    }

    public void setStartlongitude(Double startlongitude) {
        this.startlongitude = startlongitude;
    }

    public Double getEndlatitude() {
        return endlatitude;
    }

    public void setEndlatitude(Double endlatitude) {
        this.endlatitude = endlatitude;
    }

    public Double getEndlongitude() {
        return endlongitude;
    }

    public void setEndlongitude(Double endlongitude) {
        this.endlongitude = endlongitude;
    }

    public String getLatLngs() {
        return latLngs;
    }

    public void setLatLngs(String latLngs) {
        this.latLngs = latLngs;
    }

    public byte[] getNotification() {
        return notification;
    }

    public void setNotification(byte[] notification) {
        this.notification = notification;
    }

}
