package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RUN_WARING".
 */
public class RunWaring {

    private Long id;
    private String index;
    private Long createTime;
    private Double latitude;
    private Double longitude;
    private Long runId;
    private Integer lc;

    public RunWaring() {
    }

    public RunWaring(Long id) {
        this.id = id;
    }

    public RunWaring(Long id, String index, Long createTime, Double latitude, Double longitude, Long runId, Integer lc) {
        this.id = id;
        this.index = index;
        this.createTime = createTime;
        this.latitude = latitude;
        this.longitude = longitude;
        this.runId = runId;
        this.lc = lc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIndex() {
        return index;
    }

    public void setIndex(String index) {
        this.index = index;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Long getRunId() {
        return runId;
    }

    public void setRunId(Long runId) {
        this.runId = runId;
    }

    public Integer getLc() {
        return lc;
    }

    public void setLc(Integer lc) {
        this.lc = lc;
    }

}
