package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPORTS_STRUCTURE".
 */
public class SportsStructure {

    private Long id;
    private Integer type;
    private byte[] equipment;
    private String target1;
    private String target2;
    private String target3;
    private String gif;
    private Integer gif_len;
    private Integer checkNum;
    private byte[] checkX;
    private byte[] checkY;
    private byte[] checkZ;
    private Long bestTime;

    public SportsStructure() {
    }

    public SportsStructure(Long id) {
        this.id = id;
    }

    public SportsStructure(Long id, Integer type, byte[] equipment, String target1, String target2, String target3, String gif, Integer gif_len, Integer checkNum, byte[] checkX, byte[] checkY, byte[] checkZ, Long bestTime) {
        this.id = id;
        this.type = type;
        this.equipment = equipment;
        this.target1 = target1;
        this.target2 = target2;
        this.target3 = target3;
        this.gif = gif;
        this.gif_len = gif_len;
        this.checkNum = checkNum;
        this.checkX = checkX;
        this.checkY = checkY;
        this.checkZ = checkZ;
        this.bestTime = bestTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public byte[] getEquipment() {
        return equipment;
    }

    public void setEquipment(byte[] equipment) {
        this.equipment = equipment;
    }

    public String getTarget1() {
        return target1;
    }

    public void setTarget1(String target1) {
        this.target1 = target1;
    }

    public String getTarget2() {
        return target2;
    }

    public void setTarget2(String target2) {
        this.target2 = target2;
    }

    public String getTarget3() {
        return target3;
    }

    public void setTarget3(String target3) {
        this.target3 = target3;
    }

    public String getGif() {
        return gif;
    }

    public void setGif(String gif) {
        this.gif = gif;
    }

    public Integer getGif_len() {
        return gif_len;
    }

    public void setGif_len(Integer gif_len) {
        this.gif_len = gif_len;
    }

    public Integer getCheckNum() {
        return checkNum;
    }

    public void setCheckNum(Integer checkNum) {
        this.checkNum = checkNum;
    }

    public byte[] getCheckX() {
        return checkX;
    }

    public void setCheckX(byte[] checkX) {
        this.checkX = checkX;
    }

    public byte[] getCheckY() {
        return checkY;
    }

    public void setCheckY(byte[] checkY) {
        this.checkY = checkY;
    }

    public byte[] getCheckZ() {
        return checkZ;
    }

    public void setCheckZ(byte[] checkZ) {
        this.checkZ = checkZ;
    }

    public Long getBestTime() {
        return bestTime;
    }

    public void setBestTime(Long bestTime) {
        this.bestTime = bestTime;
    }

}
