package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String userID;
    private String Nickname;
    private Integer gender;
    private java.util.Date birthday;
    private Integer height;
    private Integer weight;
    private String fitness_level;
    private Integer experience;
    private Integer big_goal;
    private Integer target_weight;
    private Integer target_distance;
    private Integer target_speed;
    private Integer times;
    private String equipment;
    private Integer fields;
    private String medals;
    private String email;
    private String mobile;
    private String picturePath;
    private String loginName;
    private String password;
    private String fileName;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userID, String Nickname, Integer gender, java.util.Date birthday, Integer height, Integer weight, String fitness_level, Integer experience, Integer big_goal, Integer target_weight, Integer target_distance, Integer target_speed, Integer times, String equipment, Integer fields, String medals, String email, String mobile, String picturePath, String loginName, String password, String fileName) {
        this.id = id;
        this.userID = userID;
        this.Nickname = Nickname;
        this.gender = gender;
        this.birthday = birthday;
        this.height = height;
        this.weight = weight;
        this.fitness_level = fitness_level;
        this.experience = experience;
        this.big_goal = big_goal;
        this.target_weight = target_weight;
        this.target_distance = target_distance;
        this.target_speed = target_speed;
        this.times = times;
        this.equipment = equipment;
        this.fields = fields;
        this.medals = medals;
        this.email = email;
        this.mobile = mobile;
        this.picturePath = picturePath;
        this.loginName = loginName;
        this.password = password;
        this.fileName = fileName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getNickname() {
        return Nickname;
    }

    public void setNickname(String Nickname) {
        this.Nickname = Nickname;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getFitness_level() {
        return fitness_level;
    }

    public void setFitness_level(String fitness_level) {
        this.fitness_level = fitness_level;
    }

    public Integer getExperience() {
        return experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    public Integer getBig_goal() {
        return big_goal;
    }

    public void setBig_goal(Integer big_goal) {
        this.big_goal = big_goal;
    }

    public Integer getTarget_weight() {
        return target_weight;
    }

    public void setTarget_weight(Integer target_weight) {
        this.target_weight = target_weight;
    }

    public Integer getTarget_distance() {
        return target_distance;
    }

    public void setTarget_distance(Integer target_distance) {
        this.target_distance = target_distance;
    }

    public Integer getTarget_speed() {
        return target_speed;
    }

    public void setTarget_speed(Integer target_speed) {
        this.target_speed = target_speed;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public String getEquipment() {
        return equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    public Integer getFields() {
        return fields;
    }

    public void setFields(Integer fields) {
        this.fields = fields;
    }

    public String getMedals() {
        return medals;
    }

    public void setMedals(String medals) {
        this.medals = medals;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPicturePath() {
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

}
