package com.keenbrace.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "USER".
 */
public class User implements Serializable {

    private Long id;
    private String userID;
    private String Nickname;
    private Integer gender;
    private java.util.Date birthday;
    private Integer height;
    private Integer weight;
    private String fitness_level;
    private Integer experience;
    private Integer big_goal;
    private Integer target_weight;
    private Integer target_distance;
    private Integer target_speed;
    private Integer times;
    private String equipment;
    private Integer fields;
    private String medals;
    private String email;
    private String mobile;
    private String picturePath;
    private String loginName;
    private String password;
    private Integer goal_weight;
    private Integer goal_bodyFat;
    private Integer goal_waist;
    private Integer goal_chest;
    private Integer goal_arms;
    private Integer goal_forArms;
    private Integer goal_shoulder;
    private Integer goal_hips;
    private Integer goal_thighs;
    private Integer goal_calves;
    private Integer goal_neck;
    private String fileName;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userID, String Nickname, Integer gender, java.util.Date birthday, Integer height, Integer weight, String fitness_level, Integer experience, Integer big_goal, Integer target_weight, Integer target_distance, Integer target_speed, Integer times, String equipment, Integer fields, String medals, String email, String mobile, String picturePath, String loginName, String password, Integer goal_weight, Integer goal_bodyFat, Integer goal_waist, Integer goal_chest, Integer goal_arms, Integer goal_forArms, Integer goal_shoulder, Integer goal_hips, Integer goal_thighs, Integer goal_calves, Integer goal_neck, String fileName) {
        this.id = id;
        this.userID = userID;
        this.Nickname = Nickname;
        this.gender = gender;
        this.birthday = birthday;
        this.height = height;
        this.weight = weight;
        this.fitness_level = fitness_level;
        this.experience = experience;
        this.big_goal = big_goal;
        this.target_weight = target_weight;
        this.target_distance = target_distance;
        this.target_speed = target_speed;
        this.times = times;
        this.equipment = equipment;
        this.fields = fields;
        this.medals = medals;
        this.email = email;
        this.mobile = mobile;
        this.picturePath = picturePath;
        this.loginName = loginName;
        this.password = password;
        this.goal_weight = goal_weight;
        this.goal_bodyFat = goal_bodyFat;
        this.goal_waist = goal_waist;
        this.goal_chest = goal_chest;
        this.goal_arms = goal_arms;
        this.goal_forArms = goal_forArms;
        this.goal_shoulder = goal_shoulder;
        this.goal_hips = goal_hips;
        this.goal_thighs = goal_thighs;
        this.goal_calves = goal_calves;
        this.goal_neck = goal_neck;
        this.fileName = fileName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getNickname() {
        return Nickname;
    }

    public void setNickname(String Nickname) {
        this.Nickname = Nickname;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getFitness_level() {
        return fitness_level;
    }

    public void setFitness_level(String fitness_level) {
        this.fitness_level = fitness_level;
    }

    public Integer getExperience() {
        return experience;
    }

    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    public Integer getBig_goal() {
        return big_goal;
    }

    public void setBig_goal(Integer big_goal) {
        this.big_goal = big_goal;
    }

    public Integer getTarget_weight() {
        return target_weight;
    }

    public void setTarget_weight(Integer target_weight) {
        this.target_weight = target_weight;
    }

    public Integer getTarget_distance() {
        return target_distance;
    }

    public void setTarget_distance(Integer target_distance) {
        this.target_distance = target_distance;
    }

    public Integer getTarget_speed() {
        return target_speed;
    }

    public void setTarget_speed(Integer target_speed) {
        this.target_speed = target_speed;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public String getEquipment() {
        return equipment;
    }

    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    public Integer getFields() {
        return fields;
    }

    public void setFields(Integer fields) {
        this.fields = fields;
    }

    public String getMedals() {
        return medals;
    }

    public void setMedals(String medals) {
        this.medals = medals;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPicturePath() {
        return picturePath;
    }

    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getGoal_weight() {
        return goal_weight;
    }

    public void setGoal_weight(Integer goal_weight) {
        this.goal_weight = goal_weight;
    }

    public Integer getGoal_bodyFat() {
        return goal_bodyFat;
    }

    public void setGoal_bodyFat(Integer goal_bodyFat) {
        this.goal_bodyFat = goal_bodyFat;
    }

    public Integer getGoal_waist() {
        return goal_waist;
    }

    public void setGoal_waist(Integer goal_waist) {
        this.goal_waist = goal_waist;
    }

    public Integer getGoal_chest() {
        return goal_chest;
    }

    public void setGoal_chest(Integer goal_chest) {
        this.goal_chest = goal_chest;
    }

    public Integer getGoal_arms() {
        return goal_arms;
    }

    public void setGoal_arms(Integer goal_arms) {
        this.goal_arms = goal_arms;
    }

    public Integer getGoal_forArms() {
        return goal_forArms;
    }

    public void setGoal_forArms(Integer goal_forArms) {
        this.goal_forArms = goal_forArms;
    }

    public Integer getGoal_shoulder() {
        return goal_shoulder;
    }

    public void setGoal_shoulder(Integer goal_shoulder) {
        this.goal_shoulder = goal_shoulder;
    }

    public Integer getGoal_hips() {
        return goal_hips;
    }

    public void setGoal_hips(Integer goal_hips) {
        this.goal_hips = goal_hips;
    }

    public Integer getGoal_thighs() {
        return goal_thighs;
    }

    public void setGoal_thighs(Integer goal_thighs) {
        this.goal_thighs = goal_thighs;
    }

    public Integer getGoal_calves() {
        return goal_calves;
    }

    public void setGoal_calves(Integer goal_calves) {
        this.goal_calves = goal_calves;
    }

    public Integer getGoal_neck() {
        return goal_neck;
    }

    public void setGoal_neck(Integer goal_neck) {
        this.goal_neck = goal_neck;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

}
